name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      # This ensures all your app's packages are installed in the GitHub environment
      - name: Install dependencies
        run: npm install

      - name: Cypress run
        uses: cypress-io/github-action@v7
        with:
          start: npm start
          # UPDATED: Pointing to your actual port 8080
          wait-on: 'http://localhost:8080'
          wait-on-timeout: 60
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}